### ISSUE TITLE
debug infor for history store

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3116]
## Overview
The node would encounter bug like below.
```
java.lang.Exception: 0: cannot acquire 256 bits from a vector that contains 252 bits at coop.rchain.shared.AttemptOpsF$.ex(AttemptOpsF.scala:10) at coop.rchain.shared.AttemptOpsF$RichAttempt.get(AttemptOpsF.scala:19) at coop.rchain.rspace.history.HistoryStoreInstances$$anon$1.$anonfun$get$2(HistoryStore.scala:38) at cats.instances.OptionInstances$$anon$1.traverse(option.scala:87) at cats.instances.OptionInstances$$anon$1.traverse(option.scala:15) at cats.Traverse$Ops.traverse(Traverse.scala:19) at cats.Traverse$Ops.traverse$(Traverse.scala:19) at cats.Traverse$ToTraverseOps$$anon$2.traverse(Traverse.scala:19) at coop.rchain.rspace.history.HistoryStoreInstances$$anon$1.$anonfun$get$1(HistoryStore.scala:38) at scala.Function1.$anonfun$andThen$1(Function1.scala:57) at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:170) at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:222) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) at java.base/java.util.concurrent.FutureTask.run(Unknown Source) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```

We don't know the condition to reproduce the situation. Current solution is to put more debug info into the history store when this bug happened.

**Comment by 9rb** [comment]
https://rchain.atlassian.net/browse/RCHAIN-3952?jql=text%20~%20%22java.lang.Exception%3A%20cannot%20acquire%22  is a history of prior reports of 'java.lang.exception cannot acquire n bits from a vector that has <n bits..'
