### ISSUE TITLE
lmdb KeyValueTyped error 

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3122]
The node failed on catching up process with the exception below.
```
        at coop.rchain.store.KeyValueTypedStoreCodec.$anonfun$decodeValue$1(KeyValueTypedStoreCodec.scala:43)
        at scodec.Attempt$Failure.fold(Attempt.scala:113)
        at coop.rchain.store.KeyValueTypedStoreCodec.decodeValue(KeyValueTypedStoreCodec.scala:44)
        at coop.rchain.store.KeyValueTypedStoreCodec.$anonfun$get$8(KeyValueTypedStoreCodec.scala:55)
        at cats.instances.OptionInstances$$anon$1.traverse(option.scala:87)
        at cats.instances.OptionInstances$$anon$1.traverse(option.scala:15)
        at cats.Traverse$Ops.traverse(Traverse.scala:19)
        at cats.Traverse$Ops.traverse$(Traverse.scala:19)
        at cats.Traverse$ToTraverseOps$$anon$2.traverse(Traverse.scala:19)
        at coop.rchain.store.KeyValueTypedStoreCodec.$anonfun$get$7(KeyValueTypedStoreCodec.scala:55)
        at cats.instances.VectorInstances$$anon$1.$anonfun$traverse$2(vector.scala:80)
        at cats.instances.VectorInstances$$anon$1.loop$2(vector.scala:43)
        at cats.instances.VectorInstances$$anon$1.$anonfun$foldRight$2(vector.scala:44)
        at cats.Eval$.advance(Eval.scala:271)
        at cats.Eval$.loop$1(Eval.scala:350)
        at cats.Eval$.cats$Eval$$evaluate(Eval.scala:368)
        at cats.Eval$Defer.value(Eval.scala:257)
        at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:79)
        at cats.instances.VectorInstances$$anon$1.traverse(vector.scala:15)
        at cats.Traverse$Ops.traverse(Traverse.scala:19)
        at cats.Traverse$Ops.traverse$(Traverse.scala:19)
        at cats.Traverse$ToTraverseOps$$anon$2.traverse(Traverse.scala:19)
        at coop.rchain.store.KeyValueTypedStoreCodec.$anonfun$get$6(KeyValueTypedStoreCodec.scala:55)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:170)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
        at monix.eval.internal.TaskRestartCallback$$anon$1.run(TaskRestartCallback.scala:118)
        at monix.execution.internal.Trampoline.monix$execution$internal$Trampoline$$immediateLoop(Trampoline.scala:66)
        at monix.execution.internal.Trampoline.startLoop(Trampoline.scala:32)
        at monix.execution.schedulers.TrampolineExecutionContext$JVMOptimalTrampoline.startLoop(TrampolineExecutionContext.scala:132)
        at monix.execution.internal.Trampoline.execute(Trampoline.scala:40)
        at monix.execution.schedulers.TrampolineExecutionContext.execute(TrampolineExecutionContext.scala:57)                                                                      
        at monix.execution.schedulers.BatchingScheduler.execute(BatchingScheduler.scala:50)                                                                                        
        at monix.execution.schedulers.BatchingScheduler.execute$(BatchingScheduler.scala:47)
        at monix.execution.schedulers.ExecutorScheduler.execute(ExecutorScheduler.scala:35)
        at monix.eval.internal.TaskCreate$CallbackForCreate.startExecution(TaskCreate.scala:236)
        at monix.eval.internal.TaskCreate$CallbackForCreate.tryOnSuccess(TaskCreate.scala:202)
        at monix.eval.internal.TaskCreate$CallbackForCreate.onSuccess(TaskCreate.scala:195)
        at monix.execution.Callback.apply(Callback.scala:105)
        at monix.execution.Callback.apply(Callback.scala:82)
        at cats.effect.internals.MVarConcurrent.unsafeRead(MVarConcurrent.scala:225)
        at cats.effect.internals.MVarConcurrent.$anonfun$read$1(MVarConcurrent.scala:60)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at monix.eval.internal.TaskCreate$.$anonfun$cancelableEffect$1(TaskCreate.scala:38)
        at monix.eval.internal.TaskCreate$Cancelable0Start.apply(TaskCreate.scala:160)
        at monix.eval.internal.TaskCreate$Cancelable0Start.apply(TaskCreate.scala:147)
        at monix.eval.internal.TaskRestartCallback.start(TaskRestartCallback.scala:58)
        at monix.eval.internal.TaskRunLoop$.executeAsyncTask(TaskRunLoop.scala:592)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:120)
        at monix.eval.internal.TaskRestartCallback.syncOnSuccess(TaskRestartCallback.scala:101)
        at monix.eval.internal.TaskRestartCallback.onSuccess(TaskRestartCallback.scala:74)
        at monix.eval.internal.TaskSleep$SleepRunnable.run(TaskSleep.scala:71)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

After the exception , restart the node would show the exception below every time. 
```
java.lang.Exception: cannot acquire 426032 bits from a vector that contains 44280 bits
        at coop.rchain.store.KeyValueTypedStoreCodec.$anonfun$decodeValue$1(KeyValueTypedStoreCodec.scala:43)
        at scodec.Attempt$Failure.fold(Attempt.scala:113)
        at coop.rchain.store.KeyValueTypedStoreCodec.decodeValue(KeyValueTypedStoreCodec.scala:44)
        at coop.rchain.store.KeyValueTypedStoreCodec.$anonfun$toMap$5(KeyValueTypedStoreCodec.scala:90)
        at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
        at monix.eval.internal.TaskRunLoop$.startFull(TaskRunLoop.scala:170)
        at monix.eval.internal.TaskRunLoop$.$anonfun$restartAsync$1(TaskRunLoop.scala:222)
        at monix.execution.internal.InterceptRunnable.run(InterceptRunnable.scala:27)
        at monix.execution.internal.forkJoin.AdaptedForkJoinTask.exec(AdaptedForkJoinTask.scala:27)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)

```

logs file below
[rnode.log.tar.gz](https://github.com/rchain/rchain/files/5199802/rnode.log.tar.gz)

the logs below didn't show in the `rnode.log` but in the `docker logs`
[logs-not-shows-in-rnode.log-but-docker-logs.log](https://github.com/rchain/rchain/files/5199803/logs-not-shows-in-rnode.log-but-docker-logs.log)

### What did you expect to see?
Node runs normally

### What did you see instead?
Node failed and exited with exception

### Steps to reproduce the bug

Not sure yet. Probably start a node which tries to catch up

### What version of RNode are you using?
RChain Node 0.9.25.3 (ac92f281a1964bad0bd239819e3ed2300d83f272)

### What is your environment?

Linux Ubuntu
HDD disk

**Comment by zsluedem** [comment]
It is possible that the data file is corrupted. Leave this issue open for now for more observation.

**Comment by 9rb** [comment]
https://rchain.atlassian.net/browse/RCHAIN-3952?jql=text%20~%20%22java.lang.Exception%3A%20cannot%20acquire%22  is a history of prior reports of 'java.lang.exception cannot acquire n bits from a vector that has <n bits..'
