### ISSUE TITLE
lmdb error Platform constant error code: ENOMEM Cannot allocate memory (12)

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3257]
### What did you expect to see?
In [block-merge branch](https://github.com/rchain/rchain/tree/feature/block-merge), when you call api https://github.com/rchain/rchain/blob/5036147ceda6d85f923366451f41e09d127fd7de/casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala#L500-L532

An exception below will throw
```
21:17:04.775 [ERROR] [grpc-io-72          ] [a.DeployGrpcServiceV1$$anon$1] - Deploy service method error.
org.lmdbjava.LmdbNativeException$ConstantDerivedException: Platform constant error code: ENOMEM Cannot allocate memory (12)
        at org.lmdbjava.ResultCodeMapper.checkRc(ResultCodeMapper.java:114)
        at org.lmdbjava.Env$Builder.open(Env.java:495)
        at org.lmdbjava.Env$Builder.open(Env.java:512)
        at coop.rchain.casper.storage.LmdbStoreManagerImpl.$anonfun$createEnv$6(LmdbStoreManager.scala:130)
        at cats.effect.Sync.$anonfun$delay$1(Sync.scala:54)
        at cats.effect.Sync$KleisliSync.$anonfun$suspend$6(Sync.scala:314)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
        at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
```

The problem happens on initializing historyStore from lmdb in line https://github.com/rchain/rchain/blob/5036147ceda6d85f923366451f41e09d127fd7de/rspace/src/main/scala/coop/rchain/rspace/history/HistoryRepository.scala#L61

**Comment by zsluedem** [comment]
After talking with @tgrospic , it is very possible that the lmdb is opening the same file with two different `Env` which cause the problem

**Comment by zsluedem** [comment]
Can not reproduce this bug. Close it.
