### ISSUE TITLE
Support Apple M1

### ISSUE THREAD

**Issue by wangjia184** [rchain/rchain#3404]
Max OS BigSur , CPU Apple M1 Arm64

I made some attempt to fix the compilation isssue in apple M1.
https://github.com/wangjia184/rchain/commit/753e54c68cce7062d4b2e7da7cf0158a5be276ad

Generally `protoc` is not shipped with a pre-compiled binary, hence it has to attach to an existing `protoc` , details can be found here https://github.com/scalapb/ScalaPB/issues/1024

Still the compilation fails at [this line](https://github.com/wangjia184/rchain/blob/753e54c68cce7062d4b2e7da7cf0158a5be276ad/project/StacksafeScalapbGenerator.scala#L35): 
```
--scala_0_out: java.lang.NoSuchMethodError: 'com.google.protobuf.Descriptors$FileDescriptor com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(java.lang.String[], com.google.protobuf.Descriptors$FileDescriptor[])'
	at scalapb.options.Scalapb.<clinit>(Scalapb.java:22457)
	at scalapb.options.compiler.Scalapb$.registerAllExtensions(Scalapb.scala:8)
	at coop.rchain.scalapb.StacksafeScalapbGenerator$.registerExtensions(StacksafeScalapbGenerator.scala:35)
	at protocgen.CodeGenApp.run(CodeGenApp.scala:42)
	at protocgen.CodeGenApp.run$(CodeGenApp.scala:39)
  | => mat coop.rchain.scalapb.StacksafeScalapbGenerator$.run(StacksafeScalapbGenerator.scala:33)
  | => sat protocgen.CodeGenApp.run(CodeGenApp.scala:31)
  | => rat protocgen.CodeGenApp.run$(CodeGenApp.scala:30)
  | => mat coop.rchain.scalapb.StacksafeScalapbGenerator$.run(StacksafeScalapbGenerator.scala:33)
  | => cat protocbridge.frontend.PluginFrontend$.$anonfun$runWithBytes$1(PluginFrontend.scala:52)
	at scala.util.Try$.apply(Try.scala:213)
	at protocbridge.frontend.PluginFrontend$.runWithBytes(PluginFrontend.scala:52)
	at protocbridge.frontend.PluginFrontend$.runWithInputStream(PluginFrontend.scala:122)
	at protocbridge.frontend.PosixPluginFrontend$.$anonfun$prepare$2(PosixPluginFrontend.scala:39)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1$$anon$2.block(ExecutionContextImpl.scala:75)
	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3127)
	at scala.concurrent.impl.ExecutionContextImpl$DefaultThreadFactory$$anon$1.blockOn(ExecutionContextImpl.scala:87)
	at scala.concurrent.package$.blocking(package.scala:146)
	at protocbridge.frontend.PosixPluginFrontend$.$anonfun$prepare$1(PosixPluginFrontend.scala:37)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

I am appreciated if the project can support M1 CPU.  Currently I am using a UTM VirtualMachine to build thee project, that is very slow 

Thanks in advancced

**Comment by TheoXD** [comment]
Scala Native 0.4.4 supports M1 chip https://scala-native.readthedocs.io/en/latest/changelog/0.4.4.html#improved-arm64-support

**Comment by tgrospic** [comment]
> Scala Native 0.4.4 supports M1 chip https://scala-native.readthedocs.io/en/latest/changelog/0.4.4.html#improved-arm64-support

Unfortunately, it's a long road ahead to use Scala native to compile RNode. All dependencies must also be compiled with Scala native.
Libraries like [cats Scala native](https://github.com/typelevel/cats-effect/issues/1302) already working on the native version, I see some initial version for [scalapb](https://github.com/scalapb/ScalaPB/issues/387) also.
More challenge is probably [netty](https://github.com/netty/netty-tcnative) which is based on Tomcat written in Java.

**Comment by nzpr** [comment]
The PR above enables build on M1. The one obstacle is that installing  of jFlex and BNFC via Nix does not work
```
nix-env -i jflex -iA haskellPackages.BNFC --file https://github.com/NixOS/nixpkgs-channels/archive/nixos-20.03.tar.gz

installing 'jflex-1.7.0'
installing 'BNFC-2.8.3'
error: cannot coerce null to a string

       at /nix/store/r43ws6diif4y5mh90cbmix9yd864zkmi-source/pkgs/stdenv/generic/make-derivation.nix:191:34:

          190|         // (lib.optionalAttrs (!(attrs ? name) && attrs ? pname && attrs ? version)) {
          191|           name = "${attrs.pname}-${attrs.version}";
             |                                  ^
          192|         } // (lib.optionalAttrs (stdenv.hostPlatform != stdenv.buildPlatform && !dontAddHostSuffix && (attrs ? name || (attrs ? pname && attrs ? version)))) {
(use '--show-trace' to show detailed location information)
``` 
But you can just install latest BNFC with brew `brew install bnfc`, and install exactly version 1.7.0 from GitHub repo https://github.com/jflex-de/jflex/releases/tag/v1.7.0.
