### ISSUE TITLE
InterpreterUtilTest: pass map update test failed

### ISSUE THREAD

**Issue by nzpr** [rchain/rchain#3469]
## Overview
Test randomly failed on CI during one of routine GHA executions on PR https://github.com/rchain/rchain/pull/3468.
It is not connected to changes made in PR, so some nondeterministic bug possible. 

```
org.scalatest.exceptions.TestFailedException: None was not equal to Some(<ByteString@53ad2692 size=32 contents="?\232\343q\307\375pS<\314\257\371\257&\260\307\037\336G\n\n\225\b\345\251+E\322\300&#\336">)
	at org.scalatest.MatchersHelper$.indicateFailure(MatchersHelper.scala:346)
	at org.scalatest.Matchers$ShouldMethodHelper$.shouldMatcher(Matchers.scala:6668)
	at org.scalatest.Matchers$AnyShouldWrapper.should(Matchers.scala:6704)
	at coop.rchain.casper.util.rholang.InterpreterUtilTest.$anonfun$new$178(InterpreterUtilTest.scala:746)
	at map @ coop.rchain.casper.util.rholang.InterpreterUtilTest.$anonfun$new$177(InterpreterUtilTest.scala:745)
	at >>$extension @ coop.rchain.rholang.interpreter.RhoRuntime$.$anonfun$createRuntime$3(RhoRuntime.scala:587)
	at whenA$extension @ coop.rchain.store.LmdbDirStoreManager.$anonfun$store$6(LmdbDirStoreManager.scala:68)
	at flatMap @ coop.rchain.casper.util.rholang.InterpreterUtil$.handleErrors(InterpreterUtil.scala:134)
	at map @ coop.rchain.casper.util.rholang.InterpreterUtil$.$anonfun$validateBlockCheckpoint$13(InterpreterUtil.scala:92)
	at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
	at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
	at apply @ coop.rchain.metrics.MetricsSemaphore$.apply(MetricsSemaphore.scala:44)
	at sequence @ coop.rchain.rholang.interpreter.RhoRuntime$.introduceSystemProcesses(RhoRuntime.scala:310)
	at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
	at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
	at apply @ coop.rchain.metrics.MetricsSemaphore$.apply(MetricsSemaphore.scala:44)
	at sequence @ coop.rchain.rholang.interpreter.RhoRuntime$.introduceSystemProcesses(RhoRuntime.scala:310)
	at map @ coop.rchain.rspace.RSpaceOps.$anonfun$lockedInstall$14(RSpaceOps.scala:307)
	at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
	at sequence @ coop.rchain.rholang.interpreter.RhoRuntime$.introduceSystemProcesses(RhoRuntime.scala:310)
[info] - should pass map update test *** FAILED *** (42 seconds, 94 milliseconds)
[info]   None was not equal to Some(<ByteString@53ad2692 size=32 contents="?\232\343q\307\375pS<\314\257\371\257&\260\307\037\336G\n\n\225\b\345\251+E\322\300&#\336">) (InterpreterUtilTest.scala:746)
```

### Impact
Why test failed is not clear, but would be great to have it reproducible,

### Dependencies
-

### Design
-

### Steps to implement the solution
-

### Steps for integration testing
-

### Resource estimation
-

**Comment by zsluedem** [comment]
Do you have the ci link?

**Comment by tgrospic** [comment]
Exactly the same error output would be in case of tuple space hash mismatch error. We will see if it happens again with the fix #3526.
