### ISSUE TITLE
sequential processes run out of sequence, peeks doing persistent reads. was code does not run to completion

### ISSUE THREAD

**Issue by jimscarver** [rchain/rchain#3479]
I developed a simple message queue publish and subscribe. In a test the execution justs seems to stop randomly

I create a message queue, subscribe to it and publish four items.on it. Whether I explore or deploy I do not get complete output. Normally I receive the first two items, but sometimes just one or three.

```scala
new result, stdout(`rho:io:stdout`), mq in {
  contract mq(ret) = {
    new head, tail, pub, sub in {
      tail!(*head) |
      ret!(*pub, *sub) |
      contract sub(receiver) = {
        new loop, ack in {
          loop!(*head) |
          contract loop(curr) = {
            for (value, next <<- curr) {
              result!(["got next",*value]) |
              receiver!(*value, *ack) |
                stdout!(["got next",*value]) |
              for ( _ <- ack) {
                result!(["sent",*value]) |
                stdout!(["sent",*value]) |
                loop!(*next)
              }
            }
          }
        }
      } |
      contract pub(value, ret) = {
        new newTail in {
          for (end <- tail) {
            end!(*value, *newTail) |
            tail!(*newTail) |
            ret!(Nil)
          }
        }
      }
    }
  }|
  new receiver, ret, log, list, ack in {
    contract receiver(value, ret) = {
      stdout!(*value ++ " receiver")|
      log!(*value, *ack ) |
      for ( _ <- ack ) {
        ret!(Nil)
      }
    } |
    mq!(*ret) |
    for ( pub, sub <- ret) {
      sub!(*receiver) |
      pub!("one",*ret) |
      for ( _ <- ret) {
        pub!("two", *ret) |
        for ( _ <- ret ) {
          pub!("three", *ret) |
          for ( _ <- ret ) {
            pub!("four", *ret) |
            for ( _ <- ret ) {
              log!("done", *ret) |
              for (_ <- ret; alist <- list ) {stdout!(*alist)|result!(*alist)}
            }
          }
        }
      }
    } |
    list!([]) |
    contract log(term, ack) = {
      for ( prior <- list) {
        stdout!("log: " ++ *term) |
        list!(*prior ++ [*term]) |
        ack!(Nil)
      }
    }
  }
}
```
Result
```
[
  [ "one", "done" ],
  [ "got next", "two" ],
  [ "sent", "one" ],
  [ "got next", "one" ]
]
```
rnode.log
```
["got next", "one"]
"one receiver"
"log: one"
["sent", "one"]
"log: done"
["got next", "two"]
"two receiver"
["one", "done"]
```
### What version of RNode are you using?
version 0.10.2 (4220ea8e61c0525cddb980e97b45c6939c8f4a64)
### What is your environment?

ubuntu on windows WSL2, testnet, rhobot.net all get the same results

**Comment by jimscarver** [comment]
noe I see this in the log
```
	at coop.rchain.rholang.interpreter.compiler.NameNormalizeMatcher$.normalizeMatch(normalize.scala:272)
	at coop.rchain.rholang.interpreter.compiler.ProcNormalizeMatcher$.$anonfun$normalizeMatch$30(normalize.scala:691)
	at cats.effect.Sync$KleisliSync.$anonfun$suspend$6(Sync.scala:314)
	at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)

```
I would guess that's when the rholang execution stops.

**Comment by jimscarver** [comment]
I am not seeing that error now.

I added a peek after writes befor returning an ack that the method had completed which seems to make no difference.

I improved the naming and added logging.
```scala
new result, stdout(`rho:io:stdout`), mq in {
  contract mq(ret) = {
    new head, tail, pub, sub in {
      tail!(*head) |
      ret!(*pub, *sub) |
      contract sub(listener) = {
        new loop, ack in {
          loop!(*head) |
          contract loop(curr) = {
            for (value, next <<- curr) {
              result!(["got next",*value]) |
              listener!(*value, *ack) |
              stdout!(["got next",*value]) |
              result!("litener called for " ++ *value) |
              for ( _ <- ack) {
                result!(["sent",*value]) |
                stdout!(["sent",*value]) |
                loop!(*next)
              }
            }
          }
        }
      } |
      contract pub(value, ret) = {
        new newTail in {
          for (end <- tail) {
            end!(*value, *newTail) |
            tail!(*newTail) |
            for ( _ <<- tail) {
              ret!(Nil)
            }
          }
        }
      }
    }
  }|
  new listener, ret, logList, log, ack in {
    contract listener(value, ret) = {
      result!(*value ++ " listener")|
      log!(*value, *ack ) |
      for ( _ <- ack ) {
        ret!(Nil)
      }
    } |
    mq!(*ret) |
    for ( pub, sub <- ret) {
      sub!(*listener) |
      pub!("one",*ret) |
      for ( _ <- ret) {
        pub!("two", *ret) |
        for ( _ <- ret ) {
          pub!("three", *ret) |
          for ( _ <- ret ) {
            pub!("four", *ret) |
            for ( _ <- ret ) {
              log!("done", *ret) |
              for (_ <- ret; alist <- logList ) {
                stdout!(*alist)|
                result!({ "log":*alist})
              }
            }
          }
        }
      }
    } |
    logList!([]) |
    contract log(term, ack) = {
      for ( prior <- logList) {
        stdout!("logged: " ++ *term) |
        logList!(*prior ++ [*term]) |
        for ( _ <<- logList ) {
          ack!(Nil)
        }
      }
    }
  }
}
```
result

  [ "got next", "three" ],
  "litener called for three",
 [
  "three listener",
  "litener called for three",
  [    "got next",    "three"  ],
  {    "log": [
      "one",
      "two",
      "done"
    ]  },
  [    "sent",    "two"  ],
  "two listener",
  "litener called for two",
  [    "got next",    "two"  ],
  [    "sent",    "one"  ],
  "one listener",
  "litener called for one",
  [    "got next",    "one"  ]
]

rnode.log

"got next", "one"]
"logged: one"
["sent", "one"]
["got next", "two"]
"logged: two"
["sent", "two"]
"logged: done"
["got next", "three"]
["one", "two", "done"]
["got next", "one"]
"logged: one"
["sent", "one"]
["got next", "two"]
"logged: done"
["one", "done"]
["got next", "one"]
"logged: one"
["sent", "one"]
["got next", "two"]
"logged: two"
"logged: done"
["one", "two", "done"]
["sent", "two"]
["got next", "three"]

**Comment by zsluedem** [comment]
What did you expect to see in the first example?

**Comment by jimscarver** [comment]
> What did you expect to see in the first example?

since we got "three listener" in the result we should have seen "three" 1n log. listener never completed. "four is missing completely as if it just stopped in the middle of three.

the rnode log should have contained.

{ "log": [
"one",
"two",
"three",
"four,
"done"
] },

["sent", "three"]
["sent", "four"]
["got next", "four"]

but it never returned from receive "three"

**Comment by jimscarver** [comment]
Here is the code not reusing any return channel.
```scala
new result, stdout(`rho:io:stdout`), mq in {
  contract mq(ret) = {
    new head, tail, pub, sub in {
      tail!(*head) |
      ret!(*pub, *sub) |
      contract sub(listener) = {
        new loop, ack in {
          loop!(*head) |
          contract loop(curr) = {
            for (value, next <<- curr) {
              //result!(["got next",*value]) |
              listener!(*value, *ack) |
              stdout!(["got next",*value]) |
              result!("listener being called for " ++ *value) |
              for ( _ <- ack) {
                result!("listener returned " ++ *value) |
                stdout!(["listener returned",*value]) |
                loop!(*next)
              }
            }
          }
        }
      } |
      contract pub(value, ret) = {
        new newTail in {
          for (end <- tail) {
            end!(*value, *newTail) |
            tail!(*newTail) |
            //for ( _ <<- tail) {
              ret!(Nil)
              //}
            }
          }
        }
      }
    }|
    new listener, ret, logList, log,
    ack, ack1, ack2, ack3, ack4, ack5 in {
      contract listener(value, ret) = {
        result!(*value ++ " listener started")|
        log!(*value, *ack ) |
        for ( _ <- ack ) {
          result!(*value ++ " listener finished") |
          ret!(Nil)
        }
      } |
      mq!(*ack1) |
      for ( pub, sub <- ack1) {
        sub!(*listener) |
        pub!("one",*ack2) |
        for ( _ <- ack2) {
          pub!("two", *ack3) |
          for ( _ <- ack3) {
            pub!("three", *ack4) |
            for ( _ <- ack4) {
              pub!("four", *ack5) |
              for ( _ <- ack5) {
                log!("done", *ret) |
                for (_ <- ret; alist <- logList ) {
                  stdout!(*alist)|
                  result!({ "log":*alist})
                }
              }
            }
          }
        }
      } |
      logList!([]) |
      contract log(term, done) = {
        for ( prior <- logList) {
          result!("logged: " ++ *term) |
          logList!(*prior ++ [*term]) |
          for ( _ <<- logList ) {
            done!(Nil)
          }
        }
      }
    }
  }
  ```

##Result:
[
  "three listener started",
  "listener being called for three",
  {
    "log": [
      "one",
      "done",
      "two"
    ]
  },
  "listener returned two",
  "two listener finished",
  "logged: two",
  "logged: done",
  "two listener started",
  "listener being called for two",
  "listener returned one",
  "one listener finished",
  "logged: one",
  "one listener started",
  "listener being called for one"
]

"two" was logged and three never started. Somehow "done" was logged before "two"!!??

##A second run
[
  {
    "log": [
      "one",
      "done"
    ]
  },
  "two listener started",
  "listener being called for two",
  "logged: done",
  "listener returned one",
  "one listener finished",
  "logged: one",
  "one listener started",
  "listener being called for one"
]

The "two" listener was started but never finished.

##Another
[
  {
    "log": [
      "done"
    ]
  },
  "one listener started",
  "logged: done",
  "listener being called for one"
]

the "one" listener was started but not finished.

**Comment by jimscarver** [comment]
I commented out the unnecessary peek in log
```scala
     contract log(term, done) = {
        for ( prior <- logList) {
          result!("logged: " ++ *term) |
          logList!(*prior ++ [*term]) |
          //for ( _ <<- logList ) {
            done!(Nil)
            //}
          }
        }
```
The results look the same
```javascript
{
    "log": [
      "one",
      "done",
      "two"
    ]...
```

**Comment by jimscarver** [comment]
It was suggested that the link structure I use might be the problem.  I created a simple linkedList.rho using the same list structure. It works fine. The listener is implicated.
```scala
new result, list, log, logList, ack in {
    contract list(ret) = {
        new head, tail, first, add, isend, ack in {
            tail!(*head) |
            ret!(*first, *add, *isend) |
            contract add(value, ack) = {
                new newTail in {
                    for ( oldTail <- tail) {
                        oldTail!(*value, *newTail) |
                        tail!(*newTail) |
                        //for (_ <<- tail) {}
                            ack!(Nil)
                        //}
                    }
                }
            } |
            contract first(ret) = {
                for ( value, next <<- head ) {
                ret!(*value, *next)
                }
            } |
            contract isend(next, ret) = {
                for (end <<- tail) {
                    ret!( *end == *next)
                }
            }
            
        }
    } |
    result!("testing") |
    new ack1, ack2, ack3, ack4, ack5, ack6, ack7, ack8, ack9, ack10,
        ret1, ret2, ret3, ret4, ret5, ret6, ret7, ret8, ret9, ret10, ret in {
        list!(*ret)|
        result!("getting list") |
        for( first, add, isend <- ret) { result!("adding") |
            add!(1,*ack1)|for ( _ <- ack1) { result!("added one") |
            add!(2,*ack2)|for ( _ <- ack2) { result!("added two") |
            add!(3,*ack3)|for ( _ <- ack3) {
            add!(4,*ack4)|for ( _ <- ack4) {
            add!(5,*ack5)|for ( _ <- ack5) {
            add!(6,*ack6)|for ( _ <- ack6) {
            add!(7,*ack7)|for ( _ <- ack7) {
            add!(8,*ack8)|for ( _ <- ack8) {
            add!(9,*ack9)|for ( _ <- ack9) {
            add!(10,*ack10)|for ( _ <- ack10) {
                result!("accessing") |
                first!(*ret1) |
                for (value, ret2 <<- ret1) { log!(*value, *ack1)|
                for (value, ret3 <<- ret2) { log!(*value, *ack1)|
                for (value, ret4 <<- ret3) { log!(*value, *ack1)|
                for (value, ret5 <<- ret4) { log!(*value, *ack1)|
                for (value, ret6 <<- ret5) { log!(*value, *ack1)|
                for (value, ret7 <<- ret6) { log!(*value, *ack1)|
                for (value, ret8 <<- ret7) { log!(*value, *ack1)|
                for (value, ret9 <<- ret8) { log!(*value, *ack1)|
                for (value, ret10 <<- ret9) { log!(*value, *ack1)|
                for (value, next <<- ret10) { log!(*value, *ack1)|
                for (alist <- logList ) {
                result!({ "log":*alist})
              }
                }}}}}}}}}}
            }}}}}}}}}}
        }
    } |
    logList!([]) |
    contract log(term, ack) = {
      for ( prior <- logList) {
        result!("logged: ${x}"%%{"x": *term}) |
        logList!(*prior ++ [*term]) |
        ack!(Nil)
      }
    }
}
```

**Comment by jimscarver** [comment]
I updated the above to include the log method to rule that out as a problem as well.

**Comment by jimscarver** [comment]
I simplified mq.rho down to basics and still the listener is sent the next but is not run after one two or three pubs.
```scala
new result, stdout(`rho:io:stdout`), stdoutAck(`rho:io:stdoutAck`), log, logList, mq in {
  contract mq(ret) = {
    new head, tail, pub, sub in {
      tail!(*head) |
      ret!(*pub, *sub) |
      contract sub(listener) = {
        new loop, ack in {
          loop!(*head) |
          contract loop(curr) = {
            for (value, next <<- curr) {
              result!(["got next",*value]) |
              listener!(*value, *ack) |
              stdout!(["got next",*value]) |
              result!("listener called for " ++ *value) |
              for ( _ <- ack) {
                result!(["listener returned",*value]) |
                stdout!(["sent",*value]) |
                loop!(*next)
              }
            }
          }
        }
      } |
      contract pub(value, ret) = {
        new newTail in {
          for (end <- tail) {
            end!(*value, *newTail) |
            tail!(*newTail) |
            log!("pub: " ++ *value. ret)|            
          }
        }
      }
    }
  }|
  new listener, ret in {
    contract listener(value, ack) = {        
        result!(*value ++ " listener")|
        log!("received: " ++ value, *ack )            
    } |
    mq!(*ret) |
    for ( pub, sub <- ret) {
      sub!(*listener) |
      pub!("one",*ret) |
      for ( _ <- ret) {
        pub!("two", *ret) |
        for ( _ <- ret ) {
          pub!("three", *ret) |
          for ( _ <- ret ) {
            pub!("four", *ret) |
            for ( _ <- ret ) {
              log!("done", *ret) |
              for (_ <- ret; alist <- logList ) {
                stdout!(*alist)|
                result!({ "log":*alist})
              }
            }
          }
        }
      }
    } |
    logList!([]) |
    contract log(term, ack) = {
      for ( prior <- logList) {
        stdout!("logged: " ++ *term) |
        logList!(*prior ++ [*term]) |
        ack!(Nil)
      }
    }
  }
}
```
result:
```json
[
  {
    "log": [
      "pub: one",
      "received: one",
      "pub: two",
      "pub: three",
      "received: two",
      "pub: four",
      "done"
    ]
  },
  "three listener",
  "listener called for three",
  [    "got next", "three"  ],
  [    "listener returned",    "two"  ],
  "two listener",
  [    "got next",    "two"  ],
  "listener called for two",
  [    "listener returned",    "one"  ],
  "one listener",
  [    "got next",    "one"  ],
  "listener called for one"
]
```

**Comment by jimscarver** [comment]
I added subscribe and listen to the simple linked list. When I subscribe before making the list 6 to 9 of the 10 elements are received. Subscribing after I only receive the first..
```scala
new result, list, log, logList, ack in {
  contract list(ret) = {
    new head, tail, first, add, isend, sub, ack in {
      tail!(*head) |
      ret!(*first, *add, *isend, *sub) |
      contract add(value, ack) = {
        new newTail in {
          for ( oldTail <- tail) {
            oldTail!(*value, *newTail) |
            tail!(*newTail) |
            //for (_ <<- tail) {}
            ack!(Nil)
            //}
          }
        }
      } |
      contract first(ret) = {
        for ( value, next <<- head ) {
          ret!(*value, *next)
        }
      } |
      contract isend(next, ret) = {
        for (end <<- tail) {
          ret!( *end == *next)
        }
      } |
      contract sub(listener) = {
        new loop, ack in {
          loop!(*head) |
          contract loop(curr) = {
            for (value, next <<- curr) {
              result!(["got next",*value]) |
              listener!(*value, *ack) |
              result!("listener called for ${x}"%%{"x": *value}) |
              for ( _ <- ack) {
                result!(["listener returned",*value]) |
                loop!(*next)
              }
            }
          }
        }
      }
    }
  } |
  result!("testing") |
  new ack1, ack2, ack3, ack4, ack5, ack6, ack7, ack8, ack9, ack10,
  ret1, ret2, ret3, ret4, ret5, ret6, ret7, ret8, ret9, ret10, ret,
  listener in {
    contract listener(value, ack) = {
      result!("${x}"%%{"x": *value} ++ " listener")|
      log!("received: " ++ "${x}"%%{"x": *value}, *ack )
    } |
    list!(*ret)|
    result!("getting list") |
    for( first, add, isend, sub <- ret) { result!("adding") |
    sub!(*listener) |
    add!(1,*ack1)|for ( _ <- ack1) {
      add!(2,*ack2)|for ( _ <- ack2) {
        add!(3,*ack3)|for ( _ <- ack3) {
          add!(4,*ack4)|for ( _ <- ack4) {
            add!(5,*ack5)|for ( _ <- ack5) {
              add!(6,*ack6)|for ( _ <- ack6) {
                add!(7,*ack7)|for ( _ <- ack7) {
                  add!(8,*ack8)|for ( _ <- ack8) {
                    add!(9,*ack9)|for ( _ <- ack9) {
                      add!(10,*ack10)|for ( _ <- ack10) {
                        result!("accessing") |
                        first!(*ret1) |
                        for (value, ret2 <<- ret1) { log!(*value, *ret2)|
                        for (value, ret3 <<- ret2) { log!(*value, *ret3)|
                        for (value, ret4 <<- ret3) { log!(*value, *ret4)|
                        for (value, ret5 <<- ret4) { log!(*value, *ret5)|
                        for (value, ret6 <<- ret5) { log!(*value, *ret6)|
                        for (value, ret7 <<- ret6) { log!(*value, *ret7)|
                        for (value, ret8 <<- ret7) { log!(*value, *ret8)|
                        for (value, ret9 <<- ret8) { log!(*value, *ret9)|
                        for (value, ret10 <<- ret9) { log!(*value, *ret10)|
                        for (value, next <<- ret10) { log!(*value, *ret1)|
                        for (alist <- logList ) {
                          //sub!(*listener)|
                          result!({ "log":*alist})
                        }
                      }}}}}}}}}}
                    }}}}}}}}}}
                  }
                } |
                new listener in {
                  contract listener(value, ack) = {
                    result!("${x}"%%{"x": *value} ++ " listener")|
                    log!("received: " ++ *value, *ack )
                  }
                } |
                logList!([]) |
                contract log(term, ack) = {
                  for ( prior <- logList) {
                    result!("logged: ${x}"%%{"x": *term}) |
                    logList!(*prior ++ [*term]) |
                    ack!(Nil)
                  }
                }
              }
```
result for subscribe after adding to list
```
"testing"
"getting list"
"adding"
"accessing"
"logged: 1"
"logged: 2"
"logged: 3"
"logged: 4"
"logged: 5"
"logged: 6"
"logged: 7"
"logged: 9"
"logged: 8"
"logged: 10"
{"log" : [1, 2, 3, 4, 5, 6, 7, 9, 8, 10]}
"listener called for 1"
"1 listener"
["got next", 1]
```
result for subscribe before adding to list
```j
[
  "8 listener",
  [
    "got next",
    8
  ],
  "listener called for 8",
  {
    "log": [
      "received: 1",
      "received: 2",
      "received: 3",
      "received: 4",
      "received: 5",
      1,
      "received: 6",
      2,
      3,
      4,
      5,
      6,
      7,
      "received: 7",
      8
    ]
  },
  "logged: 8",
  [
    "listener returned",
    7
  ],
  "logged: received: 7",
  "logged: 7",
  "7 listener",
  "listener called for 7",
  [
    "got next",
    7
  ],
  "logged: 6",
  "logged: 5",
  "logged: 4",
  "logged: 3",
  "logged: 2",
  [
    "listener returned",
    6
  ],
  "logged: received: 6",
  "logged: 1",
  "6 listener",
  "listener called for 6",
  [
    "got next",
    6
  ],
  [
    "listener returned",
    5
  ],
  "logged: received: 5",
  "accessing",
  "5 listener",
  [
    "got next",
    5
  ],
  "listener called for 5",
  [
    "listener returned",
    4
  ],
  "logged: received: 4",
  "4 listener",
  "listener called for 4",
  [
    "got next",
    4
  ],
  [
    "listener returned",
    3
  ],
  "logged: received: 3",
  "3 listener",
  "listener called for 3",
  [
    "got next",
    3
  ],
  "logged: received: 2",
  [
    "listener returned",
    2
  ],
  "2 listener",
  "listener called for 2",
  [
    "got next",
    2
  ],
  "logged: received: 1",
  [
    "listener returned",
    1
  ],
  "1 listener",
  "listener called for 1",
  [
    "got next",
    1
  ],
  "adding",
  "getting list",
  "testing"
]
```

**Comment by jimscarver** [comment]
I updated (fixed) the above simplest case of rholang execution not finishing.

**Comment by jimscarver** [comment]
I have a new minimal case showing incomplete execute of rholang code. It randomly executes some of the loop values but not all.
```scala
new result(`rho:io:stdout`), log, logList, head, tail, listener in {
  tail!(*head) |
  new loop, ack in {
    loop!(*head) |
    contract loop(curr) = {
      for (value, next <- curr) {
        result!(["got next",*value]) |
        listener!(*value, *ack) |
        result!("listener called for ${x}"%%{"x": *value}) |
        for ( _ <- ack) {
          result!(["listener returned",*value]) |
          loop!(*next)
        }
      }
    }
  }
  |
  result!("testing") |
  contract listener(value, ack) = {
    result!("${x}"%%{"x": *value} ++ " listener")|
    log!("received: " ++ "${x}"%%{"x": *value}, *ack )
  } |
  head!(1,*tail)|for ( value, next1 <<- head) {
    next1!(2,*next1)|for ( value, next2 <<- next1) {
      next2!(3,*next2)|for ( value, next3 <<- next2) {
        next3!(4,*next3)|for ( value, next4 <<- next3) {
          next4!(5,*next4)|for ( value, next5 <<- next4) {
            next5!(6,*next5)|for ( value, next6 <<- next5) {
              next6!(7,*next6)|for ( value, next7 <<- next6) {
                next7!(8,*next7)|for ( value, next8 <<- next7) {
                  next8!(9,*next8)|for ( value, next9 <<- next8) {
                    next9!(10,*next9)|for ( value, next10 <<- next9) {
                      result!("done building list") |
                      for (alist <- logList ) {
                        result!({ "log":*alist})
                      }
                    }}}}}}}}}}                  
    |
    logList!([]) |
    contract log(term, ack) = {
      for ( prior <- logList) {
        result!("logged: ${x}"%%{"x": *term}) |
        logList!(*prior ++ [*term]) |
        ack!(Nil)
      }
    }
}
stdout
```
"testing"
["got next", 1]
"listener called for 1"
"1 listener"
"logged: received: 1"
["listener returned", 1]
["got next", 2]
"listener called for 2"
"2 listener"
"logged: received: 2"
["listener returned", 2]
["got next", 4]
"listener called for 4"
"4 listener"
"logged: received: 4"
["listener returned", 4]
["got next", 9]
"listener called for 9"
"9 listener"
"done building list"
{"log" : ["received: 1", "received: 2", "received: 4"]}
```

**Comment by jimscarver** [comment]
I coded the log and listener in line and we still hit the bug. Many values are never read. It is a mystery how some values are repeated or out of order in log.
```scala
new result(`rho:io:stdout`), log, logList, head, tail, listener in {
  logList!([]) |
  tail!(*head) |
  new loop, ack in {
    loop!(*head) |
    contract loop(curr) = {
      for (value, next <<- curr) {
        for ( prior <- logList) {
          result!("logged: ${x}"%%{"x": *value}) |
          logList!(*prior ++ [*value]) |
          for ( _ <<- logList) {
            ack!(Nil)
          }
        } |
        result!("log called for ${x}"%%{"x": *value}) |
        for ( _ <- ack) {
          result!("log returned for ${x}"%%{"x": *value}) |
          loop!(*next)
        }
      }
    }
  }
  |
  result!("testing") |
  head!(1,*tail)|for ( value, next <<- head) {
    next!(2,*next)|for ( value, next <<- next) {
      next!(3,*next)|for ( value, next <<- next) {
        next!(4,*next)|for ( value, next <<- next) {
          next!(5,*next)|for ( value, next <<- next) {
            next!(6,*next)|for ( value, next <<- next) {
              next!(7,*next)|for ( value, next <<- next) {
                next!(8,*next)|for ( value, next <<- next) {
                  next!(9,*next)|for ( value, next <<- next) {
                    next!(10,*next)|for ( value, next <<- next) {
                      result!("done building list") |
                      for (alist <- logList ) {
                        result!({ "log":*alist})
                      }
                    }}}}}}}}}}
                  }
                  
```
stdout1
```json
"testing"
"log called for 1"
"logged: 1"
"log returned for 1"
"log called for 3"
"logged: 3"
"log returned for 3"
"log called for 4"
"logged: 4"
"log returned for 4"
"log called for 4"
"logged: 4"
"done building list"
"log returned for 4"
{"log" : [1, 3, 4, 4]}
"log called for 7"
```
stdout2
```json
"testing"
"log called for 1"
"logged: 1"
"log returned for 1"
"log called for 3"
"logged: 3"
"log returned for 3"
"log called for 5"
"logged: 5"
"log returned for 5"
"done building list"
"log called for 6"
{"log" : [1, 3, 5]}
"testing"
"log called for 1"
"logged: 1"
"log returned for 1"
"log called for 3"
"log returned for 3"
"logged: 3"
"log called for 2"
"logged: 2"
"log returned for 2"
"log called for 8"
"logged: 8"
"done building list"
{"log" : [1, 3, 2, 8]}
"log returned for 8"
"log called for 5"
```

**Comment by jimscarver** [comment]
I see I was halting execuyion by reading the log :(

But there is still the issue of why the results are out of order.
```scala
new result(`rho:io:stdout`), log, logList, head, tail, listener in {
  logList!([]) |
  tail!(*head) |
  new loop, ack in {
    loop!(*head) |
    contract loop(curr) = {
      for (value, next <- curr) {
        for ( prior <- logList) {
          result!(["logged: ${x} prior"%%{"x": *value}] ++ *prior) |
          logList!(*prior ++ [*value]) |
          for ( _ <<- logList) {
            ack!(Nil)
          }
        } |
        result!("log called for ${x}"%%{"x": *value}) |
        for ( _ <- ack) {
          result!("log returned for ${x}"%%{"x": *value}) |
          loop!(*next)
        }
      }
    }
  }
  |
  result!("testing") |
  head!(1,*tail)|for ( value, next <<- head) {
    next!(2,*next)|for ( value, next <<- next) {
      next!(3,*next)|for ( value, next <<- next) {
        next!(4,*next)|for ( value, next <<- next) {
          next!(5,*next)|for ( value, next <<- next) {
            next!(6,*next)|for ( value, next <<- next) {
              next!(7,*next)|for ( value, next <<- next) {
                next!(8,*next)|for ( value, next <<- next) {
                  next!(9,*next)|for ( value, next <<- next) {
                    next!(10,*next)|for ( value, next <<- next) {
                      result!("done building list") |
                      for (alist <- logList ) {
                        result!({ "log":*alist}) |
                        logList!(*alist)
                      }
                    }}}}}}}}}}
                  }
                  
```
stdout
```
"testing"
"log called for 1"
["logged: 1 prior"]
"log returned for 1"
"log called for 3"
["logged: 3 prior", 1]
"log returned for 3"
"log called for 7"
["logged: 7 prior", 1, 3]
"done building list"
"log returned for 7"
{"log" : [1, 3, 7]}
"log called for 10"
["logged: 10 prior", 1, 3, 7]
"log returned for 10"
"log called for 9"
["logged: 9 prior", 1, 3, 7, 10]
"log returned for 9"
"log called for 6"
["logged: 6 prior", 1, 3, 7, 10, 9]
"log returned for 6"
"log called for 2"
["logged: 2 prior", 1, 3, 7, 10, 9, 6]
"log returned for 2"
"log called for 8"
["logged: 8 prior", 1, 3, 7, 10, 9, 6, 2]
"log returned for 8"
"log called for 4"
["logged: 4 prior", 1, 3, 7, 10, 9, 6, 2, 8]
"log returned for 4"
"log called for 5"
["logged: 5 prior", 1, 3, 7, 10, 9, 6, 2, 8, 4]
"log returned for 5"
```

**Comment by jimscarver** [comment]
I think we are getting some where. 

When I read the value,next in the loop it completes out of order having never returned the logged/prior message but somehow ack is sent.

If I peek at the value,next instead I get an infinite loop.
```scala
new result(`rho:io:stdout`), logList, head, tail, listener in {
  tail!(*head) |
  new loop, ack in {
    logList!([]) |
    loop!(*head) |
    contract loop(curr) = {
      for (value, next <- curr) {
        for ( prior <- logList) {
          result!(["logged: ${x} prior:"%%{"x": *value}],*prior) |
          logList!(*prior ++ [*value]) |
          for (_ <<- logList) {
            ack!(Nil)
          }
        } |
        result!("log called for ${x}"%%{"x": *value}) |
        for ( _ <- ack) {
          result!(["log returned",*value]) |
          loop!(*next)
        }
      }
    }
  }
  |
  result!("testing") |
  head!(1,*tail)|for ( value, next <<- head) {
    next!(2,*next)|for ( value, next <<- next) {
      next!(3,*next)|for ( value, next <<- next) {
        next!(4,*next)|for ( value, next <<- next) {
          next!(5,*next)|for ( value, next <<- next) {
            next!(6,*next)|for ( value, next <<- next) {
              next!(7,*next)|for ( value, next <<- next) {
                next!(8,*next)|for ( value, next <<- next) {
                  next!(9,*next)|for ( value, next <<- next) {
                    next!(10,*next)|for ( value, next <<- next) {
                      result!("done building list") |
                      for (alist <- logList ) {
                        result!({ "log":*alist})|
                        logList!(*alist)
                      }
                    }}}}}}}}}}
                  }
```
logList: [ 1, 6, 8, 5, 3, 2, 7, 9, 10, 4 ]
stdout:
```
"testing"
"log called for 1"
["log returned", 1]
"log called for 6"
"done building list"
["log returned", 6]
{"log" : [1, 6]}
"log called for 8"
["log returned", 8]
"log called for 5"
["log returned", 5]
"log called for 3"
["log returned", 3]
"log called for 2"
["log returned", 2]
"log called for 7"
["log returned", 7]
"log called for 9"
["log returned", 9]
"log called for 10"
["log returned", 10]
"log called for 4"
["log returned", 4]
```

**Comment by jimscarver** [comment]
using peek for the value,next in the loop above starts an infinite loop repeating
...
["log returned", 9]
"log called for 2"
["log returned", 2]
"log called for 8"
["log returned", 8]
"log called for 4"
["log returned", 4]
...
somehow it never sent logged:prior: to result but got an ack from somewhere?

**Comment by jimscarver** [comment]
My bug was sending two arguments to stdout But the issues remain of how the sequential processes ran out of order and why peeks ran persistently, looping forever.

**Comment by jimscarver** [comment]
mq.rho now seems to be working correctly to completion. It is not looping on peeks to the next link. Multiple subscriptions even seem to work correctly. https://gist.github.com/jimscarver/9c400f78d40fe647a0bdc728365d0e66

**Comment by jimscarver** [comment]
Ported to the Rust rewrite for a fresh reproduction and a regression test: rchain-community/rchain-rust#40.
