### ISSUE TITLE
Starting node on new hf1 network with lfs would get inconsistent dag error

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3483]
docker run command
```
        "run",
        "--bootstrap=rnode://ef34d5e196c8292cfe0da69d7df2e9ae6cea0be2@node0.root-shard.mainnet.rchain.coop?protocol=40400&discovery=40404",
        "--network-id=mainnet1",
        "--shard-name=root1",
        "--fault-tolerance-threshold=-1",
        "--api-enable-reporting",
        "--finalization-rate=1",
        "--max-number-of-parents=1"
```

After the node finish downloading the state and the approved block, the  node would raise error like below
```
rnode    | 05:26:01.590 [INFO ] [node-runner-28      ] [c.r.c.engine.Initializing    ] - Approved state for block #908739 (f618d141a5...) is successfully restored.
rnode    | 05:26:02.239 [INFO ] [node-runner-29      ] [c.r.c.MultiParentCasperImpl  ] - Validating block #908740 (d55b77c98f...).
rnode    | 05:26:02.654 [ERROR] [node-runner-28      ] [c.r.node.runtime.NodeRuntime ] - Caught unhandable error. Exiting. Stacktrace below.
rnode    | coop.rchain.blockstorage.dag.BlockDagInconsistencyError: DAG storage is missing hash b9df500556...
rnode    |      at coop.rchain.blockstorage.dag.BlockDagRepresentationOps$.$anonfun$lookupUnsafe$extension0$1(BlockDagRepresentationSyntax.scala:41)
rnode    |      at cats.ApplicativeError$LiftFromOptionPartially$.apply$extension(ApplicativeError.scala:305)
rnode    |      at cats.syntax.OptionOps$LiftToPartiallyApplied.apply(option.scala:374)
rnode    |      at coop.rchain.blockstorage.dag.BlockDagRepresentationOps$.$anonfun$lookupUnsafe$1(BlockDagRepresentationSyntax.scala:41)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |      at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
rnode    |
rnode exited with code 0
```

**Comment by nzpr** [comment]
This is justification regression validation,
https://github.com/rchain/rchain/blob/9b87bc8e3c21e89eeadf0c9a2842cbb3b5030672/casper/src/main/scala/coop/rchain/casper/Validate.scala#L575
It reads block number for justification of previous self message. So given 30 validators in a chain, current justification block number is N-30, and previous one N-60, which is older then 50 blocks we download.
Before we had to load much more messages so this was not visible.

So what we need to do is expand scope of blocks to download along with LFS to include not only latest messages from bonded validators, but also self-justifications of these.
