### ISSUE TITLE
Unbond after epoch would cause BlockDagInconsistencyError in HF2 branch

### ISSUE THREAD

**Issue by zsluedem** [rchain/rchain#3572]
## Overview

In 3 nodes network v1, v2, v3, v1 deploy `unbond` contract to the network and the whole network reach to epoch. After the epoch, v1 is successfully out of `activeValidators` but **v2 and v3** can not propose a block because of the error below.

```
INFO     peers:rnode.py:380 validator-1: coop.rchain.blockstorage.dag.BlockDagInconsistencyError: DAG storage is missing hash 64916d025f...
INFO     peers:rnode.py:380 validator-1: 	at coop.rchain.blockstorage.dag.BlockDagRepresentationOps$.$anonfun$lookupUnsafe$extension0$1(BlockDagRepresentationSyntax.scala:41)
INFO     peers:rnode.py:380 validator-1: 	at cats.ApplicativeError$LiftFromOptionPartially$.apply$extension(ApplicativeError.scala:305)
INFO     peers:rnode.py:380 validator-1: 	at cats.syntax.OptionOps$LiftToPartiallyApplied.apply(option.scala:374)
INFO     peers:rnode.py:380 validator-1: 	at coop.rchain.blockstorage.dag.BlockDagRepresentationOps$.$anonfun$lookupUnsafe$1(BlockDagRepresentationSyntax.scala:41)
INFO     peers:rnode.py:380 validator-1: 	at runToFuture @ coop.rchain.catscontrib.TaskContrib$TaskOps$.unsafeRunSync$extension(taskOps.scala:27)
```

The `64916d025f` is proposed by v1 before epoch change and `v2` and `v3` did get the block.

**Comment by zsluedem** [comment]
https://github.com/rchain/rchain/runs/4640542437?check_suite_focus=true 
failing example

**Comment by tgrospic** [comment]
Integration test needs to be refactored anyway so this error is not relevant anymore.
